spring.application.name=demo
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

#smtp config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thenotebookconcert@gmail.com
spring.mail.password=eikh epwk ilqr jjzk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# admin hashed password
admin.password=$2a$12$CcQSWQEu9WnKpoQzJCHXpuk6uxRMCHt3ey4FqidGGtk1NjVgc2hs2

server.port=8080
